### ISSUE TITLE
有关事件描述失真

### ISSUE THREAD

**Issue by Sunwuyuan** [turquoise-horizon/icodeshequ-history#1]
“导致社区长时间瘫痪，首页和发现页频繁崩溃”
在我印象中不符合实际，冰梨没有能力打小图灵网站，而是有人通过被特殊处理的文件将其作为作品头图提交，引发的用户端崩溃

本人记录：
https://wuyuan.dev/2022/08/01/xtlsvg/

关于疑似冰梨刷屏本人记录
https://wuyuan.dev/2022/08/06/xtlsp/

此外，小图灵曾在用户端检查开发者工具试图避免攻击，见
https://wuyuan.dev/2022/08/11/xtlf12/

我号上有关工具（刷屏器，攻击脚本）的存档，如果需要我会发成gist

**Comment by turquoise-horizon** [comment]
《有道小图灵历史》已经进行了相应更改，感谢你的反馈
